### ISSUE TITLE
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'email3' is not defined

### ISSUE THREAD

**Issue by darkhacknet** [MapleHackersoff/TLT-EuteMuinBot#1]
Hi dude ! Well I was wondering if you would be so kind to help me with this issue. 

Anytime that I send the $gmail command, I'm getting this ! 

!gmail 10 xxxxx@gmail.com test
Ignoring exception in command gmail:
Traceback (most recent call last):
  File "/home/xborland/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/xborland/TLT-EuteMuinBot/index.py", line 143, in gmail
    if(emailsch == email3):
NameError: name 'email3' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xborland/.local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "/home/xborland/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/xborland/.local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NameError: name 'email3' is not defined

**Comment by MapleHackersoff** [comment]
updated script to last version

**Comment by darkhacknet** [comment]
> updated script to last version

OK sounds good. Do I need to change some other thing in the script? I have already change the bot token.

Thanks in advance.
